package com.dhbw.dvst.models;

public enum Ausrichtung {
	KURVEOBENRECHTS, KURVEUNTENRECHTS, KURVEOBENLINKS, KURVEUNTENLINKS,
	GERADEWAAGERECHT, GERADESENKRECHT,
	KREUZUNGOBEN, KREUZUNGLINKS, KREUZUNGRECHTS, KREUZUNGUNTEN
}
