package com.dhbw.dvst.models;

import java.util.Random;

public enum Sehenswuerdigkeiten {
	
	AKROPOLIS, ANKOTWAT, ATOMIUM, AYERSROCK, BIGBEN, BRANDENBURGERTOR, CHICHENITZA, CHINESISCHEMAUER, CNTOWER, COLOSSEUM, CHRISTOREDENTOR, EIFELTURM, EMPIRESTATEBUILDING, 
	GIZEH, GERATBARRIERREEF, KLEINEMEHRJUNGFRAU, KREMEL, SCHIEFERTURM, SPHINX, STATUEOFLIBERTY, STONEHENGE, SYDNEYOPER, TAJMAHAL, WALKOFFAME
}
